services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: asp-net-mssql
    environment:
      - SA_PASSWORD=@PassWord123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_DATABASE=recipes_app_db
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mysql_data:
  postgres_data:
  mssql_data:
